### ISSUE TITLE
Adding top option

### ISSUE THREAD

**Issue by netmastan** [benwinding/pdfstamp#1]
Thank you for the simple and powerful tool. Is it possible to add top option?
example 

pdfstamp stamp \                                                                                                      
--input ./input.pdf \                                                                                  
--signature ./signature.png \                                                      
--output ./output.pdf \                                
--page 2 \                       
--top 30 \
--left 200

**Comment by benwinding** [comment]
Hi @netmastan,
Thanks for checking out the package, I've just added the feature in `pdfstamp@1.0.7`. Glad it's useful to you too!
Cheers! 👍
